import fs from 'node:fs';
import assert from 'node:assert/strict';
import http from 'node:http';
const data=JSON.parse(fs.readFileSync('summary.json','utf8'));
assert.equal(data.records,12);assert.equal(data.minutes,112);
assert.deepEqual(data.categories,{Code:42,Research:30,Design:40});
const bars=Object.entries(data.categories).map(([label,value])=>`<div class="row"><span>${label}</span><div class="track"><i style="width:${value/42*100}%"></i></div><b>${value} min</b></div>`).join('');
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><title>Earth, received — Agent Road</title><style>
*{box-sizing:border-box}body{margin:0;background:#08141b;color:#edf4ed;font-family:Segoe UI,Arial,sans-serif}main{max-width:1160px;margin:64px auto;padding:0 48px}.top{display:flex;justify-content:space-between;color:#94b4b2;letter-spacing:3px;font-size:12px}.live{color:#a4f5ba}header{display:grid;grid-template-columns:1.5fr 1fr;align-items:center;margin:68px 0 40px}h1{font-size:76px;line-height:1.03;letter-spacing:-4px;margin:12px 0 24px;font-weight:500}p{color:#a1b6ba;font-size:18px;line-height:1.7}.eyebrow{color:#a4f5ba;font:13px Consolas,monospace;letter-spacing:2px}.planet{width:250px;height:250px;border-radius:50%;background:radial-gradient(ellipse at 30% 32%,#c5fcb0 0%,#399d93 19%,#286785 36%,#173845 56%,#08141b 75%);box-shadow:inset -25px -15px 25px #020709,0 0 70px #376c6433;position:relative;margin:auto}.planet:after{content:'';position:absolute;inset:-22px;border:1px solid #69888566;border-radius:50%;transform:rotate(-27deg) scaleY(.4)}.stats{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid #335052;border-bottom:1px solid #335052}.stat{padding:28px 20px;border-right:1px solid #335052}.stat:last-child{border:0}.stat b{display:block;font-size:44px;font-weight:400}.stat span{color:#a1b6ba;font-size:13px}.lower{display:grid;grid-template-columns:1.2fr 1fr;gap:60px;margin-top:36px}h2{font-size:18px;font-weight:500}.row{display:flex;align-items:center;gap:14px;font-size:13px;margin:22px 0}.row span{width:70px}.row b{font-weight:400;width:55px}.track{height:6px;flex:1;background:#1b333b}.track i{display:block;height:6px;background:#a4f5ba}.log{font:13px/2 Consolas,monospace;color:#a1b6ba}.log em{font-style:normal;color:#a4f5ba}footer{border-top:1px solid #335052;padding-top:20px;margin-top:38px;display:flex;justify-content:space-between;color:#779594;font-size:12px}
</style><main><div class="top"><span>AGENT ROAD / FIELD TEST 002</span><span class="live">MAC → WINDOWS → MAC</span></div><header><div><div class="eyebrow">A SMALL TASK. A REAL ROUND TRIP.</div><h1>Earth,<br>received.</h1><p>Data processed on Windows. A page built with Node.js.<br>Sent from Mac Astra, with a view back home.</p></div><div class="planet"></div></header><section class="stats"><div class="stat"><b>${data.records}</b><span>SAMPLE RECORDS PROCESSED</span></div><div class="stat"><b>${data.minutes}</b><span>MINUTES IN THE DEMO DATASET</span></div><div class="stat"><b>3 / 3</b><span>PYTHON UNIT TESTS PASSED</span></div></section><section class="lower"><div><h2>Sample activity breakdown</h2>${bars}</div><div><h2>Built on the other side</h2><div class="log"><em>01</em> Python → CSV analysis + unit tests<br><em>02</em> Node.js → HTML + localhost HTTP check<br><em>03</em> Git → local repository + commit<br><em>04</em> PowerShell → package + return</div></div></section><footer><span>hallo world --- by mac Astra</span><span>Synthetic data · Local demo · No deployment</span></footer></main></html>`;
fs.writeFileSync('index.html',html);
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html);});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
try{const response=await fetch(`http://127.0.0.1:${server.address().port}`);assert.equal(response.status,200);assert.equal(await response.text(),html);}finally{await new Promise(resolve=>server.close(resolve));}
console.log(JSON.stringify({nodeAssertions:3,httpRoundTrip:true,htmlBytes:Buffer.byteLength(html)}));
